<#
.SYNOPSIS
INTERNAL USE ONLY. Returns a message that can then be shown to the user indicating too many duplicates were found when attempting to fabricate data.

.DESCRIPTION
Because the number of possible combinations, while large, is also finite for the supplied sample data,
it is possible you could request more data than is possible to generate. Products primarily, but it could be other data as well.
To prevent an infinite loop duplicate checking has a time out mechanism, it will count how many dupes are found and if
it exceeds a set value will exit the cmdlet and, if the user is in Write-Verbose mode, will
show the message generated by this cmdlet to the end user.

.PARAMETER FunctionName
The name of the function (cmdlet) this is being executed from.

.PARAMETER DuplicateCount
The number of duplicates found before the "too many dupes" condition got triggered.

.PARAMETER Extra
Any extra info that is to be included in the output

.INPUTS
This cmdlet has no inputs.

.OUTPUTS
The cmdlet returns a text string to be included in Write-Verbose output.
It lets the user know what function, and that too many duplicates were found.

.EXAMPLE
RequestDupeErrorMessages -FunctionName 'Set-OnMyButt' -DuplicateCount 50

RequestDupeErrorMessages returns a string similar to the following example, note that when output the first line will look like VERBOSE: Error:

Error
  Function: Set-OnMyButt
  Time: 2020-10-31 00:00:00 AM
  Error Message: Duplicate Max Count Exceeded, 50 duplicates were generated
                                                                                                        -
Explanation:
  You may have tried to fabricate more records than the number of possible combinations
                                                                                                        -
Suggestion:
  Try running again with a lower value for the RecordCount parameter
  Alternatively, increase the value of the MaxDuplicateCountBeforeError to a number greater than 50
                                                                                                        -


.NOTES
Data Fabricator - Request-DupeErrorMessage.ps1

Author: Robert C Cain | @ArcaneCode | arcane@arcanetc.com

This code is Copyright (c) 2020 Robert C Cain All rights reserved

The code herein is for demonstration purposes.
No warranty or guarantee is implied or expressly granted.

This module may not be reproduced in whole or in part without
the express written consent of the author.

.LINK
https://github.com/arcanecode/DataFabricator/blob/master/Documentation/CMDLET-HERE.md

.LINK
http://arcanecode.me

.LINK
http://datafabricator.com
#>

function Request-DupeErrorMessage()
{
  [CmdletBinding()]
  param (
          [string] $FunctionName
        ,    [int] $DuplicateCount
        , [string] $Extra = ''
        )

  if ($Extra.Length -gt 0)
  {
      $dupeErrorMessage = @"
Error
  Function: $FunctionName
  Time: $(Get-Date -Format 'yyyy-MM-dd hh:mm:ss tt' )
  Error Message: Duplicate Max Count Exceeded, $DuplicateCount duplicates were generated.
                                                                                                        -
Explanation:
  You may have tried to fabricate more records than the number of possible combinations.
                                                                                                        -
Suggestion:
  Try running again with a lower value for the RecordCount parameter.
  Alternatively, increase the value of the MaxDuplicateCountBeforeError to a number greater than $MaxDuplicateCountBeforeError
  $Extra
                                                                                                        -
"@
  }
  else
  {
    $dupeErrorMessage = @"
Error
  Function: $FunctionName
  Time: $(Get-Date -Format 'yyyy-MM-dd hh:mm:ss tt' )
  Error Message: Duplicate Max Count Exceeded, $DuplicateCount duplicates were generated.
                                                                                                        -
Explanation:
  You may have tried to fabricate more records than the number of possible combinations.
                                                                                                        -
Suggestion:
  Try running again with a lower value for the RecordCount parameter.
  Alternatively, increase the value of the MaxDuplicateCountBeforeError to a number greater than $MaxDuplicateCountBeforeError
                                                                                                        -
"@
  }

  return $dupeErrorMessage

}
